# Generated by Django 4.2.3 on 2023-07-10 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=64, verbose_name='Vin')),
                ('color', models.CharField(max_length=64, verbose_name='Color')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('age', models.IntegerField(max_length=64, verbose_name='Age')),
                ('breed', models.IntegerField(choices=[(1, 'Акита ину'), (2, 'Аляскинский маламут'), (3, 'Аргентинский дог'), (4, 'Доберман'), (5, 'Вельш корги пемброк'), (6, 'Такса')], verbose_name='Breed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
