# Generated by Django 4.2.3 on 2023-07-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_pet_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='vin',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Vin'),
        ),
    ]
